version: "3.9"
services:
  db:
    image: "postgres"
    tmpfs:
      - /run
      - /var/cache
    environment:
      PGDATA: /pgtmpfs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
  adminer:
    image: "adminer"
    ports:
      - "3000:8080"
    depends_on:
      - db

  email:
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"
      - "1025:1025"